#!/usr/bin/env python3
"""HM profile generator: emit a Reverb-OS home-manager fragment from the map report.

Produces a Nix module fragment that:
  - enables programs.* for mapped HM modules (git, tmux, rclone, zen-browser, ...)
  - adds home.packages for mapped apps without an HM module
  - does NOT touch anything deferred to Omarchy

Usage:
    python3 generator/gen_hm.py <mapper-report.json> [--out PATH]
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# Mapping of target_name -> HM programs.* option (from Reverb-OS ported modules)
HM_MODULES = {
    "git": "git",
    "tmux": "tmux",
    "rclone": "rclone",
    "zen-browser": "zen-browser",
    "vesktop": "vesktop",
    "copyq": "copyq",
    "lazygit": "lazygit",
    "opencode": "opencode",
    "ssh-flatten": "ssh-flatten",
    "caprine": "caprine",
    "freebuff-desktop": "freebuff-desktop",
    "editorconfig": "editorconfig",
    "hermes": "hermes",
    "hermes-gateway": "hermes-gateway",
    "memlawb": "memlawb",
    "nixcord-config": "nixcord-config",
    "tui-apps": "tui-apps",
}


def gen(report: dict) -> str:
    lines = [
        "# Auto-generated by omarchy-migrate generator/gen_hm.py",
        "# Drop into Reverb-OS as a module; entries defer to Omarchy where possible.",
        "{ config, lib, pkgs, ... }: {",
    ]
    # HM module enables
    hm_enables = []
    home_pkgs = []
    for m in report.get("map", []):
        ttype = m.get("target_type")
        name = m.get("target_name")
        if ttype == "hm_module" and name in HM_MODULES:
            opt = HM_MODULES[name]
            hm_enables.append(f"    programs.{opt}.enable = true;")
        elif ttype == "omarchy_pkg":
            home_pkgs.append(f"    pkgs.{name.replace('-', '_')}")
        elif ttype == "hm_pkg":
            home_pkgs.append(f"    pkgs.{name.replace('-', '_')}")
    if hm_enables:
        lines.append("  # HM-managed modules (your system layer)")
        lines.extend(sorted(set(hm_enables)))
    if home_pkgs:
        lines.append("  # Additive packages (Omarchy doesn't ship these)")
        lines.append("  home.packages = [")
        lines.extend(sorted(set(f"    {p}" for p in home_pkgs)))
        lines.append("  ];")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> int:
    args = sys.argv[1:]
    out = None
    if "--out" in args:
        out = Path(args[args.index("--out") + 1])
    if not args or args[0].startswith("--"):
        print("usage: generator/gen_hm.py <mapper-report.json> [--out PATH]", file=sys.stderr)
        return 2

    report = json.loads(Path(args[0]).read_text())
    fragment = gen(report)
    if out:
        out.write_text(fragment)
        print(f"wrote {out}")
    else:
        print(fragment)
    return 0


if __name__ == "__main__":
    sys.exit(main())
