#!/usr/bin/env python3
"""omnigate install — Git-based NixOS→Arch transformation executor.

Methods:
  ghost       Subvolume-based transform (NO resize — uses btrfs subvolumes)
  kexec       Headless boot ISO via kexec (serial console)
  vm          Test in QEMU with backup 9p share
  full-wipe   Backup → wipe → install (slowest, most reliable)

Usage:
  python3 install.py --method ghost --host zephyr --dry-run
  python3 install.py --method kexec --host zephyr --iso <path>
  python3 install.py --method vm --iso <path> --attach <backup>
"""
from __future__ import annotations
import json, sys, argparse, subprocess, os
from pathlib import Path
from datetime import datetime

REPO = Path(__file__).resolve().parent


def build_ghost_script(host: str, plan: dict) -> str:
    """Generate subvolume-based ghost-drive install script.

    KEY FIX: Does NOT resize the btrfs partition. Instead, creates a new
    subvolume (e.g. /dev/nvme0n1p2 → /@arch-root) and installs Arch there.
    The old NixOS @ subvolume stays intact for instant rollback.
    """
    p = plan.get("partitions", {})
    disk = p.get("current_disk", "nvme0n1")
    btrfs_part = p.get("btrfs_partition", f"/dev/{disk}p2")
    arch_subvol_name = f"@{host}-arch"
    arch_mount = f"/mnt/{host}-arch"

    services = plan.get("services", [])
    mapped = [s for s in services if s.get("status") == "mapped"]
    deferred = [s for s in services if s.get("status") == "defer"]

    lines = [
        "#!/usr/bin/env bash",
        f"# Ghost-subvolume Arch + omarchy install for {host}",
        f"# Strategy: subvolume install (NO partition resize — instant rollback via bootloader)",
        "# Generated by install.py — COMMIT + REVIEW BEFORE EXECUTING",
        "set -euo pipefail",
        "",
        "# --- Pre-flight checks ---",
        f"echo 'Target: {host} on {disk}'",
        f"df -h {btrfs_part}",
        "btrfs filesystem usage / | grep -E 'Device size|Used|Free'",
        "",
        "# 1. Create new btrfs subvolume for Arch (old NixOS @ stays intact)",
        f"btrfs subvolume create /{arch_subvol_name}",
        f"echo 'Created subvolume /{arch_subvol_name}'",
        "",
        "# 2. Mount Arch subvolume for pacstrap",
        f"mkdir -p {arch_mount}",
        f"mount -o subvol=/{arch_subvol_name} {btrfs_part} {arch_mount}",
        "",
        "# 3. Install Arch base",
        "pacstrap " + arch_mount + " base linux linux-firmware --noconfirm",
        "",
        "# 4. Create fstab with both subvolumes (Arch default + NixOS ghost)",
        f"genfstab -U {arch_mount} > {arch_mount}/etc/fstab",
        "# Add ghost-mount entry for NixOS rollback",
        f"echo '# NixOS ghost partition (readonly rollback)' >> {arch_mount}/etc/fstab",
        f"echo '{btrfs_part} {arch_mount}/nixos-legacy btrfs subvol=/@,ro 0 2' >> {arch_mount}/etc/fstab",
        "",
        "# 5. Chroot into Arch, install omarchy",
        f"arch-chroot {arch_mount} /bin/bash -c 'pacman -Syu --noconfirm grub efibootmgr'",
        f"arch-chroot {arch_mount} /bin/bash -c 'grub-install --target=x86_64-efi --efi-directory=/boot --removable'",
        f"arch-chroot {arch_mount} /bin/bash -c 'grub-mkconfig -o /boot/‌grub/grub.cfg'",
        f"echo 'Install omarchy via: curl -fsSL https://get.omarchy.dev | bash'",
        "",
        "# 6. Port services (from NixOS ghost mount)",
        f"mkdir -p {arch_mount}/nixos-legacy",
        f"# In arch chroot:",
    ]

    for svc in mapped:
        name = svc.get("name", "")
        equiv = svc.get("arch_equivalent", "")
        units = svc.get("systemd_units", [])
        target = svc.get("target_path", "")
        lines.append(f"  # {name} → {equiv}")
        if units:
            lines.append(f"  systemctl enable {' '.join(units)}")
        if target:
            lines.append(f"  mkdir -p {target}")
            if svc.get("install"):
                lines.append(f"  {svc['install']}")

    if deferred:
        lines.append("  # Deferred to omarchy (handled by omarchy setup):")
        for svc in deferred:
            lines.append(f"  # {svc.get('name')} → {svc.get('arch_equivalent')}")

    lines += [
        "",
        "# 7. Port secrets (from critical-configs backup)",
        "mkdir -p " + arch_mount + "/etc/age",
        f"  cp -a /mnt/sentry-backup/critical-configs/nixos/.age/ {arch_mount}/etc/age/",
        "mkdir -p " + arch_mount + "/etc/omnigate",
        f"  cp -a /mnt/sentry-backup/critical-configs/nixos/secretspec.toml {arch_mount}/etc/omnigate/",
        "mkdir -p " + arch_mount + "/etc/ssh",
        f"  cp -a /mnt/sentry-backup/home-j_kro/.ssh/* {arch_mount}/etc/ssh/ 2>/dev/null || true",
        "",
        "# 8. Port user configs via symlinks (NOT copies)",
        "# User preference: symlinks to ghost-mounted preserved dirs",
        f"  mkdir -p {arch_mount}/home/j_kro/.config",
        f"  rmdir {arch_mount}/home/j_kro/.config 2>/dev/null || true",
        f"  ln -sd /nixos-legacy/home/j_kro/.config {arch_mount}/home/j_kro/.config",
        f"  ln -sd /nixos-legacy/home/j_kro/.ssh {arch_mount}/home/j_kro/.ssh",
        f"  ln -sd /nixos-legacy/home/j_kro/.hermes {arch_mount}/home/j_kro/.hermes",
        "",
        "# 9. Port pipeWire fix (rt kernel params — the fix we verified)",
        f"  mkdir -p {arch_mount}/etc/pipewire/pipewire.conf.d/",
        f"  cp -a /mnt/sentry-backup/critical-configs/pipewire/99-lowlatency.conf {arch_mount}/etc/pipewire/pipewire.conf.d/ 2>/dev/null || true",
        "",
        "# 10. Add NixOS ghost entry to GRUB",
        f"  # NixOS entry already in GRUB — user selects at boot",
        f"  echo 'To rollback: boot NixOS @ subvolume via GRUB menu'",
        "",
        "# 11. Done — reboot and select Arch",
        "echo 'REBOOT NOW → select Arch from GRUB menu'",
        "echo 'Instant rollback: select NixOS from GRUB menu'",
    ]

    return "\n".join(lines) + "\n"


def build_kexec_script(host: str, plan: dict) -> str:
    """Generate kexec headless install script using serial console."""
    lines = [
        "#!/usr/bin/env bash",
        f"# kexec headless install for {host} (serial console)",
        "# Generated by install.py — HARD REBOOT, REVIEW FIRST",
        "set -euo pipefail",
        "",
        "# 1. Extract kernel + initrd from omarchy ISO",
        "ISO_PATH=${OMARCHY_ISO:-/home/j_kro/omarchy-test/omarchy-4.0.0.iso}",
        "mkdir -p /tmp/kexec-extract",
        "xorriso -osirrox on -indev $ISO_PATH -extract /arch/boot/x86_64/ /tmp/kexec-extract/ 2>/dev/null",
        "KERNEL=/tmp/kexec-extract/vmlinuz-linux-t2",
        "INITRD=/tmp/kexec-extract/initramfs-linux-t2.img",
        "",
        "# 2. Serve ISO over HTTP (from another terminal on local network)",
        "echo 'In another terminal: cd /home/j_kro/omarchy-test && python3 -m http.server 8091'",
        "echo 'Waiting for HTTP server... press Ctrl-C and start it manually if needed'",
        "",
        "# 3. Load kernel via kexec",
        "# Serial console + DHCP-less networking + ISO fetch from HTTP",
        'kmsg="console=ttyS0,115200 earlyprintk=vga ip=10.1.1.199::10.1.1.1:255.255.255.0::eth0:on"',
        'kmsg="$kmsg boot=live live.url=http://10.1.1.130:8091/omarchy-4.0.0.iso live.fetch=/omarchy-4.0.0.iso"',
        f'kexec -l $KERNEL --initrd=$INITRD --append "$kmsg" --reuse-cmdline',
        "",
        "# 4. Boot (HARD REBOOT — no rollback except power cycle)",
        'kexec -e',
    ]
    return "\n".join(lines) + "\n"


def build_vm_script(host: str, plan: dict) -> str:
    """Generate VM test script for headless QEMU with serial + 9p share."""
    lines = [
        "#!/usr/bin/env bash",
        f"# VM test for {host} — boot omarchy ISO with backup 9p share",
        "set -euo pipefail",
        "",
        'ISO_PATH=${OMARCHY_ISO:-/home/j_kro/omarchy-test/omarchy-4.0.0.iso}',
        'BACKUP_PATH=${BACKUP_PATH:-/home/j_kro/zephyr-backup}',
        "",
        "# Boot with: serial console + 9p backup share + user networking",
        "qemu-system-x86_64 \\",
        "  -machine q35,accel=kvm \\",
        "  -cpu host \\",
        "  -smp 4 \\",
        "  -m 4096 \\",
        "  -netdev user,id=net0,net=192.168.15.0/24 \\",
        "  -device virtio-net,netdev=net0 \\",
        "  -cdrom $ISO_PATH \\",
        "  -virtfs local,path=$BACKUP_PATH,security_model=passthrough,mount_tag=backup \\",
        "  -serial stdio \\",
        "  -display none",
        "",
        "# In the ISO live session: mount -t 9p backup /mnt",
    ]
    return "\n".join(lines) + "\n"


def method_vm(args: argparse.Namespace) -> int:
    """Boot the omarchy ISO in QEMU with backup data attached as 9p share."""
    iso = Path(args.iso)
    if not iso.exists():
        print(f"error: ISO not found at {iso}", file=sys.stderr)
        return 2

    qemu_cmd = [
        "qemu-system-x86_64",
        "-machine", "q35,accel=kvm",
        "-cpu", "host",
        "-smp", str(args.smp or os.cpu_count() or 4),
        "-m", str(args.mem or 4096),
        "-netdev", "user,id=net0,net=192.168.15.0/24",
        "-device", "virtio-net,netdev=net0",
        "-display", args.display or "none",
        "-serial", "stdio",
        "-boot", "d",
        "-cdrom", str(iso),
    ]

    if args.attach:
        qemu_cmd += [
            "-virtfs", f"local,path={args.attach},security_model=passthrough,mount_tag=backup",
        ]

    if args.dry_run:
        print("DRY RUN — QEMU command:")
        print("  " + " \\\n  ".join(qemu_cmd))
        if args.attach:
            print("\n  Mount in live session: mount -t 9p backup /mnt")
        return 0

    print(f"Booting omarchy ISO in QEMU")
    print(f"  ISO: {iso}")
    if args.attach:
        print(f"  Backup 9p share: mount -t 9p backup /mnt")
    print(f"  Serial: stdio (ISO TUI visible here)")
    print(f"  Display: {args.display or 'none'}")

    try:
        proc = subprocess.run(qemu_cmd, timeout=args.timeout or 300)
        return proc.returncode
    except KeyboardInterrupt:
        print("\nQEMU stopped by user")
        return 0
    except subprocess.TimeoutExpired:
        print(f"QEMU timed out after {args.timeout}s")
        return 0


def method_kexec(args: argparse.Namespace) -> int:
    """Generate kexec boot script for headless install."""
    iso = Path(args.iso) if args.iso else Path("/home/j_kro/omarchy-test/omarchy-4.0.0.iso")
    if not iso.exists():
        print(f"error: ISO not found at {iso}", file=sys.stderr)
        return 2

    iso_extract = Path("/tmp/omarchy-kexec")
    iso_extract.mkdir(exist_ok=True)

    subprocess.run([
        "xorriso", "-osirrox", "on", "-indev", str(iso),
        "-extract", "/arch/boot/x86_64/", str(iso_extract)
    ], check=False, capture_output=True)

    kernel = iso_extract / "vmlinuz-linux-t2"
    initrd = iso_extract / "initramfs-linux-t2.img"

    if not kernel.exists() or not initrd.exists():
        print(f"error: kernel/initrd not found in {iso_extract}", file=sys.stderr)
        return 2

    kmsg = args.kmsg or "console=ttyS0,115200 earlyprintk=vga"
    ip = args.ip or "10.1.1.199::10.1.1.1:255.255.255.0::eth0:on"
    iso_url = f"http://10.1.1.130:8091/{iso.name}"

    cmd_str = (
        f"kexec -l {kernel} --initrd={initrd} "
        f"--append '{kmsg} ip={ip} boot=live live.url={iso_url} live.fetch=/{iso.name}' "
        f"--reuse-cmdline"
    )

    print("\nkexec boot script:")
    print(f"  {cmd_str}")
    print(f"\nWARNING: HARD REBOOT — current NixOS session will be replaced")
    print(f"Start HTTP server first: cd {iso.parent} && python3 -m http.server 8091")

    if args.dry_run:
        return 0

    if not args.yes:
        resp = input("\nProceed with kexec boot? (yes/NO): ")
        if resp != "yes":
            print("Aborted.")
            return 0

    subprocess.run([
        "kexec", "-l", str(kernel), "--initrd", str(initrd),
        "--append", f"{kmsg} ip={ip} boot=live live.url={iso_url} live.fetch=/{iso.name}",
        "--reuse-cmdline"
    ], check=True)
    print("kexec loaded. Execute `kexec -e` to boot now.")
    return 0


def method_ghost(args: argparse.Namespace) -> int:
    """Preview or execute subvolume-based ghost transform."""
    from plan import load_mapping

    mapping = load_mapping()
    p = mapping.get("partition_defaults", {})

    print(f"Ghost-drive (subvolume method) for {args.host or 'zephyr'}")
    print(f"  Disk: {p.get('current_disk', 'nvme0n1')}")
    print(f"  Btrfs: {p.get('btrfs_partition', '/dev/nvme0n1p2')}")
    print(f"  Arch subvol: /@{args.host or 'zephyr'}-arch")
    print(f"  Method: btrfs subvolume create (NO resize)")
    print(f"\nThis is NON-DESTRUCTIVE — old NixOS @ and @home subvolumes stay intact.")
    print(f"Rollback: boot NixOS via GRUB menu entry.\n")

    if args.dry_run:
        print("Dry-run complete. To execute:")
        print(f"  python3 install.py --method ghost --host {args.host or 'zephyr'}")
        return 0

    print("This would execute the ghost-script.sh:")
    print(f"  See: rollbacks/{args.host or 'zephyr'}/ghost-script.sh")
    return 0


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="install.py", description="omnigate Stage 2/3 installer")
    p.add_argument("--method", choices=["vm", "kexec", "ghost", "full-wipe"], default="vm",
                   help="Install method (default: vm)")
    p.add_argument("--host", help="Target host (for ghost method)")
    p.add_argument("--iso", help="Path to omarchy ISO (kexec/vm)")
    p.add_argument("--attach", help="Directory to attach as 9p share (vm)")
    p.add_argument("--disk", help="Target disk (ghost)")
    p.add_argument("--size-gb", type=int, default=20, help="Arch partition/subvol size (ghost)")
    p.add_argument("--mem", type=int, default=4096, help="QEMU memory MB (vm)")
    p.add_argument("--smp", type=int, help="QEMU CPU cores (vm)")
    p.add_argument("--display", default="none", help="QEMU display backend (vm)")
    p.add_argument("--timeout", type=int, default=600, help="QEMU timeout (vm)")
    p.add_argument("--ip", help="Static IP for kexec")
    p.add_argument("--kmsg", help="Extra kernel cmdline for kexec")
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--yes", action="store_true")
    opts = p.parse_args(argv)

    if opts.method == "vm":
        return method_vm(opts)
    elif opts.method == "kexec":
        return method_kexec(opts)
    elif opts.method == "ghost":
        return method_ghost(opts)
    elif opts.method == "full-wipe":
        print("full-wipe not yet implemented — use --method ghost")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())