#!/usr/bin/env python3
"""omnigate restore — Stage 4 restore logic for omniport.

Generates executable restore scripts that copy configs, secrets, and data
from the backup location into the fresh Arch installation.
"""
from __future__ import annotations
import json
from pathlib import Path
from datetime import datetime


def build_restore_script(host: str, plan: dict, backup_source: str) -> str:
    """Generate a bash restore script that ports configs + secrets from backup.

    Args:
        host: hostname (e.g. 'zephyr')
        plan: transformation plan dict
        backup_source: e.g. 'backup:sentry:/home/j_kro/zephyr-backup'
    """
    # Parse backup source
    if backup_source.startswith("backup:"):
        parts = backup_source.replace("backup:", "").split(":")
        backup_host = parts[0]  # sentry
        backup_path = parts[1] if len(parts) > 1 else "/home/j_kro/zephyr-backup"
        if backup_host == "local":
            backup_root = backup_path
            mount_cmd = f"# Local backup at {backup_path}"
        else:
            backup_root = f"/mnt/{backup_host}-backup"
            mount_cmd = f"mkdir -p {backup_root}\nmount {backup_host}:{backup_path} {backup_root}"
    else:
        backup_root = backup_source
        mount_cmd = "# Using direct path"

    services = plan.get("services", [])
    mapped = [s for s in services if s.get("status") == "mapped"]
    secrets = plan.get("secrets", [])

    lines = [
        "#!/usr/bin/env bash",
        f"# Restore script for {host} — generated by restore.py",
        f"# Backup source: {backup_source}",
        f"# Generated: {datetime.now().isoformat()}",
        "set -euo pipefail",
        "",
        "# --- Mount backup ---",
        mount_cmd,
        "",
        "# --- Restore secrets ---",
        "mkdir -p /etc/age /etc/omnigate /etc/ssh",
        "chmod 700 /etc/age /etc/omnigate",
        "",
    ]

    # Secret restoration
    for sec in secrets:
        if not sec.get("target"):
            continue
        src = sec.get("source", "")
        tgt = sec.get("target", "")
        s_type = sec.get("type", "")

        # Map source path to backup path (real backup structure:
        # /home/j_kro/zephyr-backup/home-j_kro/ is a full home copy)
        if src.startswith("/etc/nixos/.age/"):
            backup_src = f"{backup_root}/home-j_kro/.age/{src.replace('/etc/nixos/.age/', '')}"
        elif src.startswith("/home/j_kro/"):
            backup_src = f"{backup_root}/home-j_kro/{src.replace('/home/j_kro/', '')}"
        elif src.startswith("/etc/nixos/"):
            backup_src = f"{backup_root}/home-j_kro/.config/nixos/{src.replace('/etc/nixos/', '')}"
        else:
            backup_src = f"{backup_root}/{src.lstrip('/')}"

        # Handle runtime secrets (copy to /run or /etc)
        if sec.get("runtime") or s_type == "user_env_creds":
            tgt = f"/home/j_kro/{tgt.lstrip('/home/j_kro/')}" if tgt.startswith("/home") else tgt
            lines.append(f"# {s_type}: {src} → {tgt}")
            lines.append(f"mkdir -p $(dirname {tgt})")
            lines.append(f"cp -a {backup_src} {tgt} 2>/dev/null || echo 'WARN: {src} not in backup'")
        elif "agenix" in src or "/run/" in src:
            lines.append(f"# runtime secret (from nixos-legacy ghost mount): {src}")
            lines.append(f"mkdir -p $(dirname {tgt})")
            lines.append(f"cp /mnt/nixos-legacy{src} {tgt} 2>/dev/null || true")
        else:
            lines.append(f"# {s_type}: {src} → {tgt}")
            lines.append(f"mkdir -p $(dirname {tgt})")
            lines.append(f"cp -a {backup_src} {tgt} 2>/dev/null || echo 'WARN: {src} not in backup'")
            if s_type == "age_key":
                lines.append(f"chmod 600 {tgt}")

    lines += [
        "",
        "# --- Restore service configs ---",
    ]

    # Service config restoration — SYMLINK from ghost mount (user preference)
    for svc in mapped:
        name = svc.get("name", "")
        target = svc.get("target_path", "")
        units = svc.get("systemd_units", [])

        lines.append(f"# {name} → {svc['arch_equivalent']}")
        if target:
            lines.append(f"mkdir -p $(dirname {target})")
            # Symlink from NixOS legacy ghost mount (preserves rollback)
            ghost_src = f"/mnt/nixos-legacy{target}"
            lines.append(f"# Symlink config from ghost mount (rollback-safe)")
            lines.append(f"# Config source: {svc.get('config_source', 'N/A')}")
            if units:
                for u in units:
                    lines.append(f"ln -sf /mnt/nixos-legacy/etc/systemd/system/{name}*.service /etc/systemd/system/{u} 2>/dev/null || echo 'WARN: {name} unit not found in ghost'")
            if target.endswith("/"):
                lines.append(f"ln -sfd {ghost_src} {target} 2>/dev/null || true")
            else:
                lines.append(f"ln -sf {ghost_src} {target} 2>/dev/null || true")

    lines += [
        "",
        "# --- Restore user dotfiles (SYMLINK from backup/ghost) ---",
        "ln -sfd /mnt/nixos-legacy/home/j_kro/.config /home/j_kro/.config 2>/dev/null || true",
        "ln -sfd /mnt/nixos-legacy/home/j_kro/.ssh /home/j_kro/.ssh 2>/dev/null || true",
        "ln -sfd /mnt/nixos-legacy/home/j_kro/.hermes /home/j_kro/.hermes 2>/dev/null || true",
        "",
        "# --- Enable services ---",
        "systemctl daemon-reload",
        "systemctl enable caddy pipewire-pulse wireplumber 2>/dev/null || true",
        "",
        "# --- Verify ---",
        "echo 'Restore complete. Check services:'",
        "systemctl status caddy pipewire-pulse wireplumber 2>/dev/null || true",
        "journalctl -b | tail -20",
    ]

    return "\n".join(lines) + "\n"
