#!/usr/bin/env bash
# Ghost-drive Arch + omarchy install script for zephyr
# Generated by install.py — REVIEW BEFORE EXECUTING
set -euo pipefail

# 1. Defrag + shrink btrfs
btrfs filesystem defrag -r /
btrfs filesystem resize -50G /
btrfs filesystem balance /

# 2. Create new Arch partition
parted -s /dev/nvme0n1 resizepart 2 -50G
parted -s /dev/nvme0n1 mkpart primary ext4 50G
mkfs.ext4 /dev/nvme0n1p3

# 3. Mount + install Arch base
mkdir -p /mnt/arch
mount /dev/nvme0n1p3 /mnt/arch
pacstrap /mnt/arch base linux linux-firmware --noconfirm

# 4. Mount ghost (old NixOS)
mkdir -p /mnt/arch/nixos-legacy
mount -o ro nvme1n1p2 /mnt/arch/nixos-legacy

# 5. Install omarchy
echo 'Install omarchy via repo: https://github.com/omarchy/omarchy'
echo 'Manual step: run omarchy setup wizard or apply omarchy-nix'

# 6. Port services
# flatpak → defer_omarchy
# cluster-mesh → tailscale
cp /mnt/arch/nixos-legacy/...//etc/nixos/modules/services/services.nix /etc/systemd/system/tailscaled.service 2>/dev/null || true
# recovery-specialisation → defer_omarchy
# cachix-auth → cachix
# cns-setup → tailscale
# cns-watcher → tailscale
# pcscd → pcsclite
# gaming → defer_omarchy
# opencode → openrouter-cli
# my-service → defer_omarchy
# sunshine → sunshine
# freebuff-desktop → defer_omarchy
# status-auto-update → pacman-init
# systemd-user-timeout → systemd (default)
# cluster-ca → step-ca
cp /mnt/arch/nixos-legacy/...//etc/nixos/hosts/zephyr/configuration.nix /etc/systemd/system/step-ca.service 2>/dev/null || true
# fake-backlight-bridge → defer_omarchy
# storage-assertions → defer_omarchy
# thermal-monitor → sensors + lm_sensors
# hermes-a2a → hermes-a2a-mesh
cp /mnt/arch/nixos-legacy/...//etc/nixos/hosts/zephyr/configuration.nix /etc/systemd/system/hermes-a2a.service 2>/dev/null || true
# memlawb-healthcheck → systemd timer
cp /mnt/arch/nixos-legacy/...//etc/nixos/hosts/zephyr/configuration.nix /etc/systemd/system/memlawb-healthcheck.timer 2>/dev/null || true
# gitlawb-client → gitlawb
# power-profiles-daemon → power-profiles-daemon
# llama-swap-cluster → llama-swap
# gitlawb-node → gitlawb

# 7. Port secrets
mkdir -p /etc/age /etc/omnigate
cp /mnt/arch/nixos-legacy/etc/nixos/.age/key.txt /etc/age/keys.txt 2>/dev/null || true
cp /mnt/arch/nixos-legacy/etc/nixos/secretspec.toml /etc/omnigate/secretspec.toml 2>/dev/null || true

# 8. Install bootloader entries
efibootmgr -c -L 'Arch Omarchy' -l /vmlinuz-linux -u 'root=PARTUUID=$(blkid -s PARTUUID -o value /dev/nvme0n1p3) rw'
efibootmgr -c -L 'NixOS (rollback)' -l /vmlinuz-linux -u 'config=...' 

# 9. Enable services
systemctl enable caddy pipewire-pulse wireplumber

# 10. First reboot → select Arch from boot menu
echo 'REBOOT NOW — select Arch Omarchy from boot menu'
echo 'To rollback: boot NixOS entry'
