#!/usr/bin/env bash
# Restore script for zephyr — generated by restore.py
# Backup source: backup:sentry:/home/j_kro/zephyr-backup
# Generated: 2026-08-22T06:47:19.626405
set -euo pipefail

# --- Mount backup ---
mkdir -p /mnt/sentry-backup
mount sentry:/home/j_kro/zephyr-backup /mnt/sentry-backup

# --- Restore secrets ---
mkdir -p /etc/age /etc/omnigate /etc/ssh
chmod 700 /etc/age /etc/omnigate

# secretspec_toml: /etc/nixos/secretspec.toml → /etc/omnigate/secretspec.toml
mkdir -p $(dirname /etc/omnigate/secretspec.toml)
cp -a /mnt/sentry-backup/critical-configs/nixos/secretspec.toml /etc/omnigate/secretspec.toml 2>/dev/null || echo 'WARN: /etc/nixos/secretspec.toml not in backup'
# age_key: /etc/nixos/.age/key.txt → /etc/age/keys.txt
mkdir -p $(dirname /etc/age/keys.txt)
cp -a /mnt/sentry-backup/critical-configs/nixos/.age/key.txt /etc/age/keys.txt 2>/dev/null || echo 'WARN: /etc/nixos/.age/key.txt not in backup'
chmod 600 /etc/age/keys.txt

# --- Restore service configs ---
# cluster-mesh → tailscale
cp /mnt/sentry-backup/critical-configs/.../cluster-mesh.service /etc/systemd/system/tailscaled.service 2>/dev/null || echo 'WARN: cluster-mesh service unit not found'
mkdir -p /etc/systemd/system/tailscale.service
cp -r /mnt/sentry-backup/critical-configs/..../cluster-mesh/* /etc/systemd/system/tailscale.service/ 2>/dev/null || true
# cachix-auth → cachix
mkdir -p /etc/cachix/cachix.conf
cp -r /mnt/sentry-backup/critical-configs/..../cachix-auth/* /etc/cachix/cachix.conf/ 2>/dev/null || true
# cns-watcher → tailscale
mkdir -p /etc/systemd/system/cns-watcher.service
cp -r /mnt/sentry-backup/critical-configs/..../cns-watcher/* /etc/systemd/system/cns-watcher.service/ 2>/dev/null || true
# pcscd → pcsclite
mkdir -p /etc/systemd/system/pcscd.service
cp -r /mnt/sentry-backup/critical-configs/..../pcscd/* /etc/systemd/system/pcscd.service/ 2>/dev/null || true
# opencode → openrouter-cli
mkdir -p /etc/systemd/system/opencode.service
cp -r /mnt/sentry-backup/critical-configs/..../opencode/* /etc/systemd/system/opencode.service/ 2>/dev/null || true
# sunshine → sunshine
mkdir -p /etc/systemd/system/sunshine.service
cp -r /mnt/sentry-backup/critical-configs/..../sunshine/* /etc/systemd/system/sunshine.service/ 2>/dev/null || true
# cluster-ca → step-ca
cp /mnt/sentry-backup/critical-configs/.../cluster-ca.service /etc/systemd/system/step-ca.service 2>/dev/null || echo 'WARN: cluster-ca service unit not found'
mkdir -p /etc/step/config/ca.json
cp -r /mnt/sentry-backup/critical-configs/..../cluster-ca/* /etc/step/config/ca.json/ 2>/dev/null || true
# thermal-monitor → sensors + lm_sensors
mkdir -p /etc/systemd/system/healthd.service
cp -r /mnt/sentry-backup/critical-configs/..../thermal-monitor/* /etc/systemd/system/healthd.service/ 2>/dev/null || true
# hermes-a2a → hermes-a2a-mesh
cp /mnt/sentry-backup/critical-configs/.../hermes-a2a.service /etc/systemd/system/hermes-a2a.service 2>/dev/null || echo 'WARN: hermes-a2a service unit not found'
mkdir -p /etc/systemd/system/hermes-a2a.service
cp -r /mnt/sentry-backup/critical-configs/..../hermes-a2a/* /etc/systemd/system/hermes-a2a.service/ 2>/dev/null || true
# memlawb-healthcheck → systemd timer
cp /mnt/sentry-backup/critical-configs/.../memlawb-healthcheck.service /etc/systemd/system/memlawb-healthcheck.timer 2>/dev/null || echo 'WARN: memlawb-healthcheck service unit not found'
mkdir -p /etc/systemd/system/memlawb-healthcheck.timer
cp -r /mnt/sentry-backup/critical-configs/..../memlawb-healthcheck/* /etc/systemd/system/memlawb-healthcheck.timer/ 2>/dev/null || true
# gitlawb-client → gitlawb
mkdir -p /etc/systemd/system/gitlawb-client.service
cp -r /mnt/sentry-backup/critical-configs/..../gitlawb-client/* /etc/systemd/system/gitlawb-client.service/ 2>/dev/null || true
# power-profiles-daemon → power-profiles-daemon
mkdir -p /etc/systemd/system/power-profiles-daemon.service
cp -r /mnt/sentry-backup/critical-configs/..../power-profiles-daemon/* /etc/systemd/system/power-profiles-daemon.service/ 2>/dev/null || true
# llama-swap-cluster → llama-swap
mkdir -p /etc/systemd/system/llama-swap@.service
cp -r /mnt/sentry-backup/critical-configs/..../llama-swap-cluster/* /etc/systemd/system/llama-swap@.service/ 2>/dev/null || true
# gitlawb-node → gitlawb
mkdir -p /etc/systemd/system/gitlawb-node@.service
cp -r /mnt/sentry-backup/critical-configs/..../gitlawb-node/* /etc/systemd/system/gitlawb-node@.service/ 2>/dev/null || true

# --- Restore user dotfiles ---
rsync -avz /mnt/backup/home-j_kro/.config /home/j_kro/.config/ 2>/dev/null || true
rsync -avz /mnt/backup/home-j_kro/.ssh /home/j_kro/.ssh/ 2>/dev/null || true
rsync -avz /mnt/backup/home-j_kro/.hermes /home/j_kro/.hermes/ 2>/dev/null || true

# --- Enable services ---
systemctl daemon-reload
systemctl enable caddy pipewire-pulse wireplumber 2>/dev/null || true

# --- Verify ---
echo 'Restore complete. Check services:'
systemctl status caddy pipewire-pulse wireplumber 2>/dev/null || true
journalctl -b | tail -20
