#!/usr/bin/env bash
# Restore script for zephyr — generated by restore.py
# Backup source: backup:local:/home/j_kro/zephyr-backup
# Generated: 2026-08-22T22:01:27.018165
set -euo pipefail

# --- Mount backup ---
# Local backup at /home/j_kro/zephyr-backup

# --- Restore secrets ---
mkdir -p /etc/age /etc/omnigate /etc/ssh
chmod 700 /etc/age /etc/omnigate

# secretspec_toml: /etc/nixos/secretspec.toml → /etc/omnigate/secretspec.toml
mkdir -p $(dirname /etc/omnigate/secretspec.toml)
cp -a /home/j_kro/zephyr-backup/home-j_kro/.config/nixos/secretspec.toml /etc/omnigate/secretspec.toml 2>/dev/null || echo 'WARN: /etc/nixos/secretspec.toml not in backup'
# age_key: /etc/nixos/.age/key.txt → /etc/age/keys.txt
mkdir -p $(dirname /etc/age/keys.txt)
cp -a /home/j_kro/zephyr-backup/home-j_kro/.age/key.txt /etc/age/keys.txt 2>/dev/null || echo 'WARN: /etc/nixos/.age/key.txt not in backup'
chmod 600 /etc/age/keys.txt

# --- Restore service configs ---
# flatpak → defer_omarchy
# cluster-mesh → tailscale
mkdir -p $(dirname /etc/systemd/system/tailscale.service)
# Symlink config from ghost mount (rollback-safe)
# Config source: None
ln -sf /mnt/nixos-legacy/etc/systemd/system/cluster-mesh*.service /etc/systemd/system/tailscaled.service 2>/dev/null || echo 'WARN: cluster-mesh unit not found in ghost'
ln -sf /mnt/nixos-legacy/etc/systemd/system/tailscale.service /etc/systemd/system/tailscale.service 2>/dev/null || true
# recovery-specialisation → defer_omarchy
# cachix-auth → cachix
mkdir -p $(dirname /etc/cachix/cachix.conf)
# Symlink config from ghost mount (rollback-safe)
# Config source: None
ln -sf /mnt/nixos-legacy/etc/cachix/cachix.conf /etc/cachix/cachix.conf 2>/dev/null || true
# cns-setup → tailscale
# cns-watcher → tailscale
mkdir -p $(dirname /etc/systemd/system/cns-watcher.service)
# Symlink config from ghost mount (rollback-safe)
# Config source: None
ln -sf /mnt/nixos-legacy/etc/systemd/system/cns-watcher.service /etc/systemd/system/cns-watcher.service 2>/dev/null || true
# pcscd → pcsclite
mkdir -p $(dirname /etc/systemd/system/pcscd.service)
# Symlink config from ghost mount (rollback-safe)
# Config source: None
ln -sf /mnt/nixos-legacy/etc/systemd/system/pcscd.service /etc/systemd/system/pcscd.service 2>/dev/null || true
# gaming → defer_omarchy
# opencode → openrouter-cli
mkdir -p $(dirname /etc/systemd/system/opencode.service)
# Symlink config from ghost mount (rollback-safe)
# Config source: None
ln -sf /mnt/nixos-legacy/etc/systemd/system/opencode.service /etc/systemd/system/opencode.service 2>/dev/null || true
# my-service → defer_omarchy
# sunshine → sunshine
mkdir -p $(dirname /etc/systemd/system/sunshine.service)
# Symlink config from ghost mount (rollback-safe)
# Config source: None
ln -sf /mnt/nixos-legacy/etc/systemd/system/sunshine.service /etc/systemd/system/sunshine.service 2>/dev/null || true
# freebuff-desktop → defer_omarchy
# status-auto-update → pacman-init
# systemd-user-timeout → systemd (default)
# cluster-ca → step-ca
mkdir -p $(dirname /etc/step/config/ca.json)
# Symlink config from ghost mount (rollback-safe)
# Config source: None
ln -sf /mnt/nixos-legacy/etc/systemd/system/cluster-ca*.service /etc/systemd/system/step-ca.service 2>/dev/null || echo 'WARN: cluster-ca unit not found in ghost'
ln -sf /mnt/nixos-legacy/etc/step/config/ca.json /etc/step/config/ca.json 2>/dev/null || true
# fake-backlight-bridge → defer_omarchy
# storage-assertions → defer_omarchy
# thermal-monitor → sensors + lm_sensors
mkdir -p $(dirname /etc/systemd/system/healthd.service)
# Symlink config from ghost mount (rollback-safe)
# Config source: None
ln -sf /mnt/nixos-legacy/etc/systemd/system/healthd.service /etc/systemd/system/healthd.service 2>/dev/null || true
# hermes-a2a → hermes-a2a-mesh
mkdir -p $(dirname /etc/systemd/system/hermes-a2a.service)
# Symlink config from ghost mount (rollback-safe)
# Config source: None
ln -sf /mnt/nixos-legacy/etc/systemd/system/hermes-a2a*.service /etc/systemd/system/hermes-a2a.service 2>/dev/null || echo 'WARN: hermes-a2a unit not found in ghost'
ln -sf /mnt/nixos-legacy/etc/systemd/system/hermes-a2a.service /etc/systemd/system/hermes-a2a.service 2>/dev/null || true
# memlawb-healthcheck → systemd timer
mkdir -p $(dirname /etc/systemd/system/memlawb-healthcheck.timer)
# Symlink config from ghost mount (rollback-safe)
# Config source: None
ln -sf /mnt/nixos-legacy/etc/systemd/system/memlawb-healthcheck*.service /etc/systemd/system/memlawb-healthcheck.timer 2>/dev/null || echo 'WARN: memlawb-healthcheck unit not found in ghost'
ln -sf /mnt/nixos-legacy/etc/systemd/system/memlawb-healthcheck.timer /etc/systemd/system/memlawb-healthcheck.timer 2>/dev/null || true
# gitlawb-client → gitlawb
mkdir -p $(dirname /etc/systemd/system/gitlawb-client.service)
# Symlink config from ghost mount (rollback-safe)
# Config source: None
ln -sf /mnt/nixos-legacy/etc/systemd/system/gitlawb-client.service /etc/systemd/system/gitlawb-client.service 2>/dev/null || true
# power-profiles-daemon → power-profiles-daemon
mkdir -p $(dirname /etc/systemd/system/power-profiles-daemon.service)
# Symlink config from ghost mount (rollback-safe)
# Config source: None
ln -sf /mnt/nixos-legacy/etc/systemd/system/power-profiles-daemon.service /etc/systemd/system/power-profiles-daemon.service 2>/dev/null || true
# llama-swap-cluster → llama-swap
mkdir -p $(dirname /etc/systemd/system/llama-swap@.service)
# Symlink config from ghost mount (rollback-safe)
# Config source: None
ln -sf /mnt/nixos-legacy/etc/systemd/system/llama-swap@.service /etc/systemd/system/llama-swap@.service 2>/dev/null || true
# gitlawb-node → gitlawb
mkdir -p $(dirname /etc/systemd/system/gitlawb-node@.service)
# Symlink config from ghost mount (rollback-safe)
# Config source: None
ln -sf /mnt/nixos-legacy/etc/systemd/system/gitlawb-node@.service /etc/systemd/system/gitlawb-node@.service 2>/dev/null || true

# --- Restore user dotfiles (SYMLINK from backup/ghost) ---
ln -sfd /mnt/nixos-legacy/home/j_kro/.config /home/j_kro/.config 2>/dev/null || true
ln -sfd /mnt/nixos-legacy/home/j_kro/.ssh /home/j_kro/.ssh 2>/dev/null || true
ln -sfd /mnt/nixos-legacy/home/j_kro/.hermes /home/j_kro/.hermes 2>/dev/null || true

# --- Enable services ---
systemctl daemon-reload
systemctl enable caddy pipewire-pulse wireplumber 2>/dev/null || true

# --- Verify ---
echo 'Restore complete. Check services:'
systemctl status caddy pipewire-pulse wireplumber 2>/dev/null || true
journalctl -b | tail -20
